Add DEIS demographic confirmed COVID-19 deaths in RM
jorgeperezrojas/covid19-data pull request #17
Opened 2020-06-21 22:48 UTC by alonsosilvaallende

Add DEIS demographic data on confirmed COVID-19 deaths in R.M.
Respondiendo el llamado a la transcripcionatón.

2020-06-23 15:56 UTC, sanguineti commented
Hola @alonsosilvaallende gracias por el aporte. Por favor actualiza tu fork y luego haz un rebase de tus cambios con respecto al último commit de `origin/master` y podemos mergear.

2020-06-23 16:39 UTC, sanguineti requested changes
lo dicho en el comentario anterior

2020-06-23 22:56 UTC, alonsosilvaallende commented
Muchas gracias @sanguineti  
No tengo idea cómo hacer eso que me pides. Alguna referencia o ayuda?

2020-06-24 01:35 UTC, sanguineti commented
> Muchas gracias @sanguineti
> No tengo idea cómo hacer eso que me pides. Alguna referencia o ayuda?

Si te es muy complicado, puedo cerrar el PR y agregar tus dos commits directamente a la rama principal.

2020-06-24 10:30 UTC, pareyesv commented
@alonsosilvaallende aquí hay una mini-guía:
https://stackoverflow.com/a/7244456/6715335

2020-06-24 21:35 UTC, alonsosilvaallende commented
Parece que logré hacer lo que me pedías @sanguineti ?
Muchas gracias @pareyesv

2020-06-24 21:42 UTC, sanguineti approved these changes

2020-06-24 21:43 UTC, merged

2020-06-24 21:44 UTC, sanguineti commented
Gracias! ya está mergeado